// <auto-generated />
using ApiDePago.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiDePago.Migrations
{
    [DbContext(typeof(ContextoDetallePago))]
    [Migration("20210518080121_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiDePago.Models.DetalleDePago", b =>
                {
                    b.Property<int>("IDPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoSeguridad")
                        .HasColumnType("nvarchar (3)");

                    b.Property<string>("NombreTarjeta")
                        .HasColumnType("nvarchar (25)");

                    b.Property<string>("NumeroTarjeta")
                        .HasColumnType("nvarchar (16)");

                    b.Property<string>("VencimientoTarjeta")
                        .HasColumnType("nvarchar (5)");

                    b.HasKey("IDPago");

                    b.ToTable("detalleDePagos");
                });
#pragma warning restore 612, 618
        }
    }
}
